//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod menu;
pub mod permission;
pub mod role;
pub mod role_menu;
pub mod role_permission;
pub mod user;
pub mod user_role;
