//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::menu::Entity as Menu;
pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::role_menu::Entity as RoleMenu;
pub use super::role_permission::Entity as RolePermission;
pub use super::user::Entity as User;
pub use super::user_role::Entity as UserRole;
